### ISSUE TITLE
Crash when a polygon contains NaN

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#1410]
This causes a crash on Linux, but not on Mac, and only in release mode:

```
polygon([[0,0], [10,0], [20, 0/0]]);
```

Relevant parts of stack trace:
```
#5  0x00007ffff3605af6 in __cxa_rethrow () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00000000005e5ec2 in ClipperLib::ClipperBase::AddPath (this=this@entry=0x7fffffffb330, pg=..., PolyTyp=PolyTyp@entry=ClipperLib::ptSubject, Closed=Closed@entry=true) at src/polyclipping/clipper.cpp:1086
#7  0x00000000005e5f7f in ClipperLib::ClipperBase::AddPaths (this=this@entry=0x7fffffffb330, ppg=..., PolyTyp=PolyTyp@entry=ClipperLib::ptSubject, Closed=Closed@entry=true) at src/polyclipping/clipper.cpp:1235
#8  0x00000000004a0164 in ClipperUtils::sanitize (paths=...) at src/clipper-utils.cc:33
#9  0x00000000004a01d3 in ClipperUtils::sanitize (poly=...) at src/clipper-utils.cc:27
#10 0x0000000000501568 in GeometryEvaluator::visit (this=0x7fffffffbc70, state=..., node=...) at src/GeometryEvaluator.cc:476
```

**Comment by MichaelAtOz** [comment]
Crashes on Windows too.
