### ISSUE TITLE
error parsing date

### ISSUE THREAD

**Issue by dposea** [openscad/openscad#1595]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\FreeCAD 0.15\Mod\OpenSCAD\importCSG.py", line 73, in open
    if workaroundforissue128needed():
  File "C:\Program Files\FreeCAD 0.15\Mod\OpenSCAD\OpenSCADUtils.py", line 91, in workaroundforissue128needed
    year,mon=int(vdate[0]),int(vdate[1])
<type 'exceptions.ValueError'>: invalid literal for int() with base 10: '03-2'

Date expected format is 2017.03.02

Sorry if this is a known issue, but I wanted to be sure it was reported

**Comment by dposea** [comment]
never mind, freecad issue, not openscad
