### ISSUE TITLE
"double free or corruption (!prev)" error on rendering

### ISSUE THREAD

**Issue by fermino** [openscad/openscad#3610]
Okay, so I managed to break openscad. I dind't find any guidelines to open an issue so if I'm missing anything please let me know!

I'm trying to make a napkin holder based on an STL model I found online, and when I try to render it, OpenScad crashes with a `double free or corruption (!prev)` error. 
I'm trying several formats but I guess it has to do with the render process and not the exporting. 
I'm using version 2019.05 and during the day I'll try to compile from master and see what happens. 

Are there any debugging options I should try?

I'm using `Arch Linux x86_64, kernel 5.10.6`. 
Command: `openscad -o test.stl test.scad`
Base STL: https://drive.google.com/file/d/1w9HAwxckBXagVjwZzJJ6hB-n8p7NxTUh/view?usp=sharing
From: https://www.thingiverse.com/thing:3585875
Code: 
```
napkinHolder("SLC_TEMPLE_revised.stl", 5, 5, 50, 189.6, 118.0, 188.7, 0, 104.1, 0, 18);

module napkinHolder(model, bottom_t, wall_t, width, mx, my, mz, mxoff, myoff, mzoff, off, rot = false)
{
	clearance = 2;
	// TODO: Add chamfer
	union() {
		// The base
		translate([0, 0, bottom_t/2])
		cube([width, my+clearance, bottom_t], center=true);

		// Load the model in both sides
		translate([0, 0, bottom_t]) {
			disp = width/2 - wall_t-clearance;
			translate([-disp, 0, 0])
			napkinHolderSide(model, mx, my, mz, mxoff, myoff, mzoff, off, wall_t, false, rot);

			translate([disp, 0, 0])
			napkinHolderSide(model, mx, my, mz, mxoff, myoff, mzoff, off, wall_t, true, rot);
		}
	}
}

module napkinHolderSide(model, mx, my, mz, mxoff, myoff, mzoff, off, final_thickness, flip = false, rot = false)
{
	// To do: rotate => rotate the model 90 degrees on load
	rotate([0, 0, (flip ? 180 : 0)])
	// We'll scale the thickness of the model
	scale([final_thickness / off, 1, 1])
	difference() {
		// Center it and offset it by off
		translate([-off, -my/2, 0])
		// Move the model to 0, 0, 0
		translate([-mxoff, -myoff, -mzoff])
		import(model);

		// Take a slice
		translate([0, -my/2, -1])
		cube([mx-off, my, mz+2]);
	}
}
```
Dump with `openscad --info`
```
QObject::startTimer: Timers can only be used with threads started with QThread
OpenSCAD Version: 2019.05
System information: Linux 5.10.6-arch1-1 #1 SMP PREEMPT Sat, 09 Jan 2021 18:22:35 +0000 x86_64 Arch Linux 4 CPUs 14.59 GB RAM
User Agent: OpenSCAD/2019.05 (Linux x86_64; Arch Linux)
Compiler: GCC "10.2.0" 64bit
MinGW build: No
Debug build: Yes
Boost version: 1_75
Eigen version: 3.3.9
CGAL version, kernels: 4.14.2, Cartesian<Gmpq>, Extended_cartesian<Gmpq>, Epeck
OpenCSG version: OpenCSG 1.4.2
Qt version: 5.15.2
QScintilla version: 2.11.6
InputDrivers: 
GLib version: 2.66.3
lodepng version: 20180910
libzip version: 1.7.3
fontconfig version: 2.13.91
freetype version: 2.10.4
harfbuzz version: 2.7.2 (runtime: 2.7.4)
lib3mf version: 1.8.1
Application Path: /usr/bin
Documents Path: /home/fermino/.local/share
User Documents Path: /home/fermino
Resource Path: /usr/share/openscad
User Library Path: /home/fermino/.local/share/OpenSCAD/libraries
User Config Path: /home/fermino/.config/OpenSCAD
Backup Path: /home/fermino/.local/share/OpenSCAD/backups
OPENSCADPATH: <not set>
OpenSCAD library path:
  /home/fermino/.local/share/OpenSCAD/libraries
  /usr/share/openscad/libraries

OPENSCAD_FONT_PATH: <not set>
OpenSCAD font path:
  /usr/share/fonts
  /usr/local/share/fonts
  /home/fermino/.local/share/fonts
  /home/fermino/.fonts
  /usr/X11/lib/X11/fonts
  /System/Library/Fonts
  /Library/Fonts
  /home/fermino/Library/Fonts
  /usr/share/fonts/100dpi
  /usr/share/fonts/75dpi
  /usr/share/fonts/TTF
  /usr/share/fonts/adobe-source-code-pro
  /usr/share/fonts/cantarell
  /usr/share/fonts/encodings
  /usr/share/fonts/gnu-free
  /usr/share/fonts/kanjistrokeorders
  /usr/share/fonts/noto
  /usr/share/fonts/util
  /usr/share/fonts/encodings/large


GLEW version: 2.2.0
OpenGL Version: 4.5 (Compatibility Profile) Mesa 20.3.2
GL Renderer: AMD KAVERI (DRM 2.50.0, 5.10.6-arch1-1, LLVM 11.0.0)
GL Vendor: AMD
RGBA(8888), depth(24), stencil(8)
GL_ARB_framebuffer_object: yes
GL_EXT_framebuffer_object: yes
GL_EXT_packed_depth_stencil: yes
GL context creator: GLX
PNG generator: lodepng
GLX version: 1.4
OS info: Linux 5.10.6-arch1-1 #1 SMP PREEMPT Sat, 09 Jan 2021 18:22:35 +0000
Machine: x86_64
```
Debug output: 
```
openscad -o servilletero-test1.amf servilletero.scad --debug=all
Debug on. --debug=all
Camera: Camera()
openscad: BuiltinContext:
Context: 0x7ffc5ca1ddf0 (0)
  document path: 
  vars:
    PI = 3.14159
    $vpd = 500
    $vpr = [0, 0, 0]
    $vpt = [0, 0, 0]
    $preview = false
    $t = 0
    $fa = 12
    $fs = 2
    $fn = 0

nodecache: NodeCache insert {5,[64:98]}
nodecache: NodeCache insert {4,[8:99]}
nodecache: NodeCache insert {14,[454:574]}
nodecache: NodeCache insert {13,[395:575]}
nodecache: NodeCache insert {12,[337:576]}
nodecache: NodeCache insert {16,[633:675]}
nodecache: NodeCache insert {15,[576:676]}
nodecache: NodeCache insert {11,[324:677]}
nodecache: NodeCache insert {10,[263:678]}
nodecache: NodeCache insert {9,[209:679]}
nodecache: NodeCache insert {8,[209:679]}
nodecache: NodeCache insert {7,[153:680]}
nodecache: NodeCache insert {24,[982:1102]}
nodecache: NodeCache insert {23,[923:1103]}
nodecache: NodeCache insert {22,[865:1104]}
nodecache: NodeCache insert {26,[1161:1203]}
nodecache: NodeCache insert {25,[1104:1204]}
nodecache: NodeCache insert {21,[852:1205]}
nodecache: NodeCache insert {20,[791:1206]}
nodecache: NodeCache insert {19,[735:1207]}
nodecache: NodeCache insert {18,[735:1207]}
nodecache: NodeCache insert {17,[680:1208]}
nodecache: NodeCache insert {6,[99:1209]}
nodecache: NodeCache insert {3,[0:1210]}
nodecache: NodeCache insert {2,[0:1210]}
nodecache: NodeCache insert {1,[0:1210]}
GeometryCache: Geometry Cache insert: cube(size=[50,120,5],center=true); (728 bytes)
GeometryCache: Geometry Cache insert: import(file="SLC_TEMPLE_revised.stl",lay (5325128 bytes)
GeometryCache: Geometry Cache insert: multmatrix([[1,0,0,0],[0,1,0,-104.1],[0, (5325128 bytes)
GeometryCache: Geometry Cache insert: cube(size=[171.6,118,190.7],center=false (728 bytes)
GeometryCache: Geometry Cache insert: multmatrix([[1,0,0,-18],[0,1,0,-59],[0,0 (5325128 bytes)
GeometryCache: Geometry Cache insert: multmatrix([[1,0,0,0],[0,1,0,-59],[0,0,1 (728 bytes)
cgalutils: Polyhedron is closed: 1
cgalutils: Polyhedron is valid: 1
GeometryUtils: add: (0,1)
GeometryUtils: add: (1,2)
GeometryUtils: add: (2,3)
GeometryUtils: add: (3,0)
GeometryUtils: Contour: 4

GeometryUtils: 0 (3) 1 (1) 2 (2)
GeometryUtils: add: (1,3)
GeometryUtils: remove: (1,2)
GeometryUtils: remove: (2,3)
GeometryUtils: 1 (1) 0 (3) 3 (0)
GeometryUtils: remove: (1,3)
GeometryUtils: remove: (3,0)
GeometryUtils: remove: (0,1)
GeometryUtils: add: (4,5)
GeometryUtils: add: (5,6)
GeometryUtils: add: (6,7)
GeometryUtils: add: (7,4)
GeometryUtils: Contour: 4

GeometryUtils: 0 (7) 1 (5) 2 (6)
GeometryUtils: add: (5,7)
GeometryUtils: remove: (5,6)
GeometryUtils: remove: (6,7)
GeometryUtils: 1 (5) 0 (7) 3 (4)
GeometryUtils: remove: (5,7)
GeometryUtils: remove: (7,4)
GeometryUtils: remove: (4,5)
GeometryUtils: add: (7,6)
GeometryUtils: add: (6,1)
GeometryUtils: add: (1,0)
GeometryUtils: add: (0,7)
GeometryUtils: Contour: 4

GeometryUtils: 0 (7) 1 (1) 2 (0)
GeometryUtils: add: (1,7)
GeometryUtils: remove: (1,0)
GeometryUtils: remove: (0,7)
GeometryUtils: 1 (1) 0 (7) 3 (6)
GeometryUtils: remove: (1,7)
GeometryUtils: remove: (7,6)
GeometryUtils: remove: (6,1)
GeometryUtils: add: (6,5)
GeometryUtils: add: (5,2)
GeometryUtils: add: (2,1)
GeometryUtils: add: (1,6)
GeometryUtils: Contour: 4

GeometryUtils: 0 (1) 1 (5) 2 (2)
GeometryUtils: add: (5,1)
GeometryUtils: remove: (5,2)
GeometryUtils: remove: (2,1)
GeometryUtils: 1 (5) 0 (1) 3 (6)
GeometryUtils: remove: (5,1)
GeometryUtils: remove: (1,6)
GeometryUtils: remove: (6,5)
GeometryUtils: add: (5,4)
GeometryUtils: add: (4,3)
GeometryUtils: add: (3,2)
GeometryUtils: add: (2,5)
GeometryUtils: Contour: 4

GeometryUtils: 0 (5) 1 (3) 2 (2)
GeometryUtils: add: (3,5)
GeometryUtils: remove: (3,2)
GeometryUtils: remove: (2,5)
GeometryUtils: 1 (3) 0 (5) 3 (4)
GeometryUtils: remove: (3,5)
GeometryUtils: remove: (5,4)
GeometryUtils: remove: (4,3)
GeometryUtils: add: (4,7)
GeometryUtils: add: (7,0)
GeometryUtils: add: (0,3)
GeometryUtils: add: (3,4)
GeometryUtils: Contour: 4

GeometryUtils: 0 (7) 1 (3) 2 (4)
GeometryUtils: add: (3,7)
GeometryUtils: remove: (3,4)
GeometryUtils: remove: (4,7)
GeometryUtils: 1 (3) 0 (7) 3 (0)
GeometryUtils: remove: (3,7)
GeometryUtils: remove: (7,0)
GeometryUtils: remove: (0,3)
double free or corruption (!prev)
[2]    10204 abort (core dumped)  openscad -o servilletero-test1.amf servilletero.scad --debug=all

**Comment by t-paul** [comment]
https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/FAQ#Reporting_bugs,_Requesting_features

I guess you covered most of it already. However it would be useful to know which OS/Distribution.

**Comment by t-paul** [comment]
Oh, please add the call that triggers the issue. The code above only has the module definitions.

**Comment by fermino** [comment]
Thanks!
I just updated the post, the module call was inlined with the code tag so it didn't display, I added the system info and the info dump too. 

I'll try this out using the windows build to see if the same thing happens. If so, I'll move on to compiling from master.

**Comment by thehans** [comment]
I was able to reproduce the crash on latest build.  

As is often the case with CGAL related errors, the STL you are using appears to have some bad geometry in it.

I imported just the STL file by itself, previewed with F12 "Thrown Together" mode (this highlights backwards faces which is useful for diagnosing mesh problems).
Everything looked reasonable from the outside, but when I positioned the camera inside the model (only possible with perspective view), I see what looks like coincident back/front faces on the center towers: 
![issue3610](https://user-images.githubusercontent.com/252233/104512155-652eb980-55b3-11eb-854a-49e353ba1e61.png)


Regardless, we do try to avoid crashing even on invalid input, so I ran a debug build and got a backtrace:
```C++
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff4c3f859 in __GI_abort () at abort.c:79
#2  0x00007ffff4caa3ee in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff4dd4285 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff4cb247c in malloc_printerr (str=str@entry=0x7ffff4dd6690 "double free or corruption (!prev)") at malloc.c:5347
#4  0x00007ffff4cb412c in _int_free (av=0x7fffdc000020, p=0x7fffb78a6b80, have_lock=<optimized out>) at malloc.c:4317
#5  0x00000000017cf650 in __gnu_cxx::new_allocator<CGAL::internal::In_place_list_iterator<CGAL::SNC_in_place_list_shalfedge<CGAL::SNC_indexed_items::SHalfedge<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > >, std::allocator<CGAL::SNC_in_place_list_shalfedge<CGAL::SNC_indexed_items::SHalfedge<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > > > > >::deallocate(CGAL::internal::In_place_list_iterator<CGAL::SNC_in_place_list_shalfedge<CGAL::SNC_indexed_items::SHalfedge<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > >, std::allocator<CGAL::SNC_in_place_list_shalfedge<CGAL::SNC_indexed_items::SHalfedge<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > > > >*, unsigned long) (this=0x7fffe171b960, __p=0x7fffb78a6b90, __t=479)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/ext/new_allocator.h:133
#6  0x00000000017cf628 in std::allocator_traits<std::allocator<CGAL::internal::In_place_list_iterator<CGAL::SNC_in_place_list_shalfedge<CGAL::SNC_indexed_items::SHalfedge<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > >, std::allocator<CGAL::SNC_in_place_list_shalfedge<CGAL::SNC_indexed_items::SHalfedge<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > > > > > >::deallocate(std::allocator<CGAL::internal::In_place_list_iterator<CGAL::SNC_in_place_list_shalfedge<CGAL::SNC_indexed_items::SHalfedge<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > >, std::allocator<CGAL::SNC_in_place_list_shalfedge<CGAL::SNC_indexed_items::SHalfedge<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > > > > >&, CGAL::internal::In_place_list_iterator<CGAL::SNC_in_place_list_shalfedge<CGAL::SNC_indexed_items::SHalfedge<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > >, std::allocator<CGAL::SNC_in_place_list_shalfedge<CGAL::SNC_indexed_items::SHalfedge<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > > > >*, unsigned long) (__a=..., __p=0x7fffb78a6b90, __n=479) at /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/alloc_traits.h:492
#7  0x00000000017cf2eb in std::_Vector_base<CGAL::internal::In_place_list_iterator<CGAL::SNC_in_place_list_shalfedge<CGAL::SNC_indexed_items::SHalfedge<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > >, std::allocator<CGAL::SNC_in_place_list_shalfedge<CGAL::SNC_indexed_items::SHalfedge<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > > > >, std::allocator<CGAL::internal::In_place_list_iterator<CGAL::SNC_in_place_list_shalfedge<CGAL::SNC_indexed_items::SHalfedge<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > >, std::allocator<CGAL::SNC_in_place_list_shalfedge<CGAL::SNC_indexed_items::SHalfedge<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > > > > > >::_M_deallocate(CGAL::internal::In_place_list_iterator<CGAL::SNC_in_place_list_shalfedge<CGAL::SNC_indexed_items::SHalfedge<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > >, std::allocator<CGAL::SNC_in_place_list_shalfedge<CGAL::SNC_indexed_items::SHalfedge<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > > > >*, unsigned long)
    (this=0x7fffe171b960, __p=0x7fffb78a6b90, __n=479) at /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_vector.h:354
#8  0x00000000017cf94d in std::_Vector_base<CGAL::internal::In_place_list_iterator<CGAL::SNC_in_place_list_shalfedge<CGAL::SNC_indexed_items::SHalfedge<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > >, std::allocator<CGAL::SNC_in_place_list_shalfedge<CGAL::SNC_indexed_items::SHalfedge<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > > > >, std::allocator<CGAL::internal::In_place_list_iterator<CGAL::SNC_in_place_list_shalfedge<CGAL::SNC_indexed_items::SHalfedge<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > >, std::allocator<CGAL::SNC_in_place_list_shalfedge<CGAL::SNC_indexed_items::SHalfedge<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > > > > > >::~_Vector_base() (this=0x7fffe171b960) at /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_vector.h:335
#9  0x00000000017ced1c in std::vector<CGAL::internal::In_place_list_iterator<CGAL::SNC_in_place_list_shalfedge<CGAL::SNC_indexed_items::SHalfedge<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > >, std::allocator<CGAL::SNC_in_place_list_shalfedge<CGAL::SNC_indexed_items::SHalfedge<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > > > >, std::allocator<CGAL::internal::In_place_list_iterator<CGAL::SNC_in_place_list_shalfedge<CGAL::SNC_indexed_items::SHalfedge<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > >, std::allocator<CGAL::SNC_in_place_list_shalfedge<CGAL::SNC_indexed_items::SHalfedge<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > > > > > >::~vector() (this=0x7fffe171b960) at /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_vector.h:683
#10 0x00000000017db087 in CGAL::SNC_FM_decorator<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> >::create_facet_objects(CGAL::Plane_3<CGAL::Cartesian<CGAL::Gmpq> > const&, std::_List_iterator<CGAL::Object>, std::_List_iterator<CGAL::Object>) constPython Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer': 
Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer': 
 (this=0x7fffe171c018, plane_supporting_facet=..., start=, end=) at /usr/include/CGAL/Nef_3/SNC_FM_decorator.h:670
#11 0x00000000017d4a7a in CGAL::SNC_external_structure<CGAL::SNC_indexed_items, CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> >::categorize_facet_cycles_and_create_facets() const (this=0x7fffe171c888)
    at /usr/include/CGAL/Nef_3/SNC_external_structure.h:1272
#12 0x00000000018de921 in CGAL::SNC_external_structure<CGAL::SNC_indexed_items, CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> >::build_after_binary_operation<CGAL::ID_support_handler<CGAL::SNC_indexed_items, CGAL::SNC_decorator<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > > >(CGAL::ID_support_handler<CGAL::SNC_indexed_items, CGAL::SNC_decorator<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > >&) (this=0x7fffe171c888, A=...) at /usr/include/CGAL/Nef_3/SNC_external_structure.h:1396
#13 0x00000000019ecd2f in CGAL::Binary_operation<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> >::operator()<CGAL::Nef_polyhedron_3<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool>::DIFF>(CGAL::SNC_point_locator<CGAL::SNC_decorator<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > >*, CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> const&, CGAL::SNC_point_locator<CGAL::SNC_decorator<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > > const*, CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> const&, CGAL::SNC_point_locator<CGAL::SNC_decorator<CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> > > const*, CGAL::Nef_polyhedron_3<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool>::DIFF const&)
    (this=0x7fffe171cea0, pl0=0x7fffb790a060, snc1=..., pl1=0x7fffac832380, snc2=..., pl2=0x7fffb78e7600, BOP=...) at /usr/include/CGAL/Nef_3/Binary_operation.h:573
#14 0x00000000019ea551 in CGAL::Nef_polyhedron_3<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool>::difference(CGAL::Nef_polyhedron_3<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> const&) const
    (this=0x7fffde62ce80, N1=...) at /usr/include/CGAL/Nef_polyhedron_3.h:1466
#15 0x00000000019d664b in CGAL::Nef_polyhedron_3<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool>::operator-(CGAL::Nef_polyhedron_3<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> const&) const
    (this=0x7fffde62ce80, N1=...) at /usr/include/CGAL/Nef_polyhedron_3.h:1502
#16 0x00000000019d4dcc in CGAL_Nef_polyhedron::operator-=(CGAL_Nef_polyhedron const&) (this=0x7fffce4a5b20, other=...) at /home/hans/projects/openscad_master/src/CGAL_Nef_polyhedron.cc:40
#17 0x00000000018209ed in CGALUtils::applyOperator3D(std::__cxx11::list<std::pair<AbstractNode const*, std::shared_ptr<Geometry const> >, std::allocator<std::pair<AbstractNode const*, std::shared_ptr<Geometry const> > > > const&, OpenSCADOperator)Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer': 
 (children=std::__cxx11::list, op=OpenSCADOperator::DIFFERENCE) at /home/hans/projects/openscad_master/src/cgalutils-applyops.cc:121
#18 0x0000000001aa7f7e in GeometryEvaluator::applyToChildren3D(AbstractNode const&, OpenSCADOperator) (this=0x7fffe171e5b8, node=..., op=OpenSCADOperator::DIFFERENCE) at /home/hans/projects/openscad_master/src/GeometryEvaluator.cc:172
#19 0x0000000001aa7662 in GeometryEvaluator::applyToChildren(AbstractNode const&, OpenSCADOperator) (this=0x7fffe171e5b8, node=..., op=OpenSCADOperator::DIFFERENCE) at /home/hans/projects/openscad_master/src/GeometryEvaluator.cc:119
#20 0x0000000001aaacf9 in GeometryEvaluator::visit(State&, CsgOpNode const&) (this=0x7fffe171e5b8, state=..., node=...) at /home/hans/projects/openscad_master/src/GeometryEvaluator.cc:666
#21 0x00000000013c0c0a in BaseVisitable::acceptImpl<CsgOpNode>(State&, CsgOpNode const&, BaseVisitor&) (state=..., node=..., visitor=...) at /home/hans/projects/openscad_master/src/BaseVisitable.h:30
#22 0x00000000013c0b25 in CsgOpNode::accept(State&, BaseVisitor&) const (this=0x4036850, state=..., visitor=...) at /home/hans/projects/openscad_master/src/csgops.h:9
#23 0x000000000166a049 in NodeVisitor::traverse(AbstractNode const&, State const&) (this=0x7fffe171e5b8, node=..., state=...) at /home/hans/projects/openscad_master/src/NodeVisitor.cc:30
#24 0x0000000001669f53 in NodeVisitor::traverse(AbstractNode const&, State const&) (this=0x7fffe171e5b8, node=..., state=...) at /home/hans/projects/openscad_master/src/NodeVisitor.cc:20
#25 0x0000000001669f53 in NodeVisitor::traverse(AbstractNode const&, State const&) (this=0x7fffe171e5b8, node=..., state=...) at /home/hans/projects/openscad_master/src/NodeVisitor.cc:20
#26 0x0000000001669f53 in NodeVisitor::traverse(AbstractNode const&, State const&) (this=0x7fffe171e5b8, node=..., state=...) at /home/hans/projects/openscad_master/src/NodeVisitor.cc:20
#27 0x0000000001669f53 in NodeVisitor::traverse(AbstractNode const&, State const&) (this=0x7fffe171e5b8, node=..., state=...) at /home/hans/projects/openscad_master/src/NodeVisitor.cc:20
#28 0x0000000001669f53 in NodeVisitor::traverse(AbstractNode const&, State const&) (this=0x7fffe171e5b8, node=..., state=...) at /home/hans/projects/openscad_master/src/NodeVisitor.cc:20
#29 0x0000000001669f53 in NodeVisitor::traverse(AbstractNode const&, State const&) (this=0x7fffe171e5b8, node=..., state=...) at /home/hans/projects/openscad_master/src/NodeVisitor.cc:20
#30 0x0000000001669f53 in NodeVisitor::traverse(AbstractNode const&, State const&) (this=0x7fffe171e5b8, node=..., state=...) at /home/hans/projects/openscad_master/src/NodeVisitor.cc:20
#31 0x0000000001669f53 in NodeVisitor::traverse(AbstractNode const&, State const&) (this=0x7fffe171e5b8, node=..., state=...) at /home/hans/projects/openscad_master/src/NodeVisitor.cc:20
#32 0x0000000001aa6adc in GeometryEvaluator::evaluateGeometry(AbstractNode const&, bool) (this=0x7fffe171e5b8, node=..., allownef=true) at /home/hans/projects/openscad_master/src/GeometryEvaluator.cc:63
#33 0x0000000001af333a in CGALWorker::work() (this=0x2fc1c90) at /home/hans/projects/openscad_master/src/cgalworker.cc:35
#34 0x00000000012ae824 in CGALWorker::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x2fc1c90, _c=QMetaObject::InvokeMetaMethod, _id=2, _a=0x7fffe171e840) at OpenSCAD_autogen/UVLADIE3JM/moc_cgalworker.cpp:87
#35 0x00007ffff5409300 in QMetaObject::activate(QObject*, int, int, void**) (sender=0x2fc6b50, signalOffset=<optimized out>, local_signal_index=<optimized out>, argv=<optimized out>) at kernel/qobject.cpp:3804
#36 0x00007ffff52135ae in QThread::started(QThread::QPrivateSignal) (this=this@entry=0x2fc6b50, _t1=...) at .moc/moc_qthread.cpp:162
#37 0x00007ffff52159ba in QThreadPrivate::start(void*) (arg=0x2fc6b50) at thread/qthread_unix.cpp:356
#38 0x00007ffff4c00609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#39 0x00007ffff4d3c293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

From my library info: `CGAL version, kernels: 5.0.2, Cartesian<Gmpq>, Extended_cartesian<Gmpq>, Epeck`

**Comment by MichaelAtOz** [comment]
The STL has self-intersections (red), and duplicate triangles (purple), also has 91 shells, so lots

of the bits may not be attached, although the other problems may cause that count to be wrong.

 



 

  _____

**Comment by MichaelAtOz** [comment]
Definitely something dodgy in my emails, it drops the images.
This was in my last post:
The STL has self-intersections (red), and duplicate triangles (purple)
![#3610 si   dup](https://user-images.githubusercontent.com/1972961/104530329-d9269b80-565f-11eb-8f5b-03e2e639c3f6.png)

**Comment by fermino** [comment]
Thank you guys for the info! I'll see if there's any online fixer that works (already tried a couple and no luck there). I guess I could try to do it manually but quite honestly I would know where to start. 

Any hints?

Aside from that, should I close the issue or keep it open so maybe this error is somehow catched in a future release?

**Comment by MichaelAtOz** [comment]
Leave this open, as thehans said, it shouldn't crash on such STL issues; 
when fixed it will still either generate an error message or bad export tho.

I've never had much luck fixing self-intersections manually, I don't have the
patience. I'd look for another model.

**Comment by kintel** [comment]
Status as of 2024-03-24: Works with both CGAL and Manifold
