### ISSUE TITLE
Documentation download script fails

### ISSUE THREAD

**Issue by gyscos** [openscad/openscad#4214]
The documentation download scripts tries to fetch https://files.openscad.org/documentation/manual.zip, but as of today on my machine, this URL just returns a HTML page depicting a 503 error:

```html
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 Resource temporarily unavailable</title>
  </head>
  <body>
    <h1>Error 503 Resource temporarily unavailable</h1>
    <p>Resource temporarily unavailable</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-ewr18147-EWR 1640614937 4002800351</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```

As a result the script fails to extract this file, which is not a valid zip file.

To reproduce, try building with `-DOFFLINE_DOCS=ON`:

```
Traceback (most recent call last):
  File "/path/to/openscad/resources/docs/docs_downloader.py", line 40, in <module>
    shutil.unpack_archive(file_name, docs_dir, 'zip')
  File "/usr/lib/python3.10/shutil.py", line 1262, in unpack_archive
    func(filename, extract_dir, **dict(format_info[2]))
  File "/usr/lib/python3.10/shutil.py", line 1170, in _unpack_zipfile
    raise ReadError("%s is not a zip file" % filename)
shutil.ReadError: manual.zip is not a zip file
```

Note: the issue seems to have since been resolved, as that manual.zip file is once again available.
It would still be nice not to depend on an external server to generate documentation, but I suppose that's another issue.

**Comment by gyscos** [comment]
The file seems to be invalid again. Seems to be a different file though; it includes (among a lot of other things):

```html
      <p><strong>No server is currently available to service your request.</strong></p>
      <p>Sorry about that. Please try refreshing and contact us if the problem persists.</p>
      <div id="suggestions">
        <a href="https://github.com/contact">Contact Support</a> &mdash;
        <a href="https://www.githubstatus.com">GitHub Status</a> &mdash;
        <a href="https://twitter.com/githubstatus">@githubstatus</a>
      </div>
```

How is the documentation generated? From a separate repository?
